travis:
  secure:
    BINSTAR_TOKEN: HsXVd28SMUBLsyuGvHIO8fB4ZKkpEyQKZ1ePZeI9Mvuqi9cLB6FIVH+QsSJoij1Y+9S08yH9MknwIOaINNj+Mgili65Nzh6p/qR8aNvzxs+bK1E8+G+qok9U6OU/rGS+omlLtmKuVv/tLI+7aD5Mdbw4ltildd4LEJJIjMdTAOzL7WcutrNFw1lWf96RXCtD0QxjaHPKe+utUKScLaQQ8nqHGnwmhonmG3t08XiLE4fyx9njbp5Fcg8XBXDBVArgMllE8SR3vi3UURvi+bKXJ9hPRSUhmzFcY+Ibv6UQKF5HfXJjAeH5q5RH6iiJxC+ALJZzSgMc8h0QTogmPGclqbiYSo3cIrbQAsG1YNyh/PA1hgTdBqO0YjHxtkRg1/HwVQecRNMbFsD3XzwuQrSgBmdbZdfKfoRRkuHCOV6Zar4mOInLliE430RPz8bZ19D6rpngCo3oKGXiJRqJ23wMQO4uzD2nj+Um7eLXxSsdHNnI7osVIkG6c9nxwFmBXWl9wlNGvLvv5Mro7k2grrIkKiQf+CLldcSfEsaXbNtsNevyWfbe7qQocUO90CJJ5IHxYAT5+Sph9/42+p4uiQk/ZVSLlMjWPFJAvwLBNssxGJSmRp0UTaeOfyS4U8K2s07pLd557R5/Ipzve7IWwad2CjhtfNExX/XE4nTR/tr58l0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
