travis:
  secure:
    BINSTAR_TOKEN: bKu1MdZXQoiK3/sw5RdJb4Hg4hYl80JzntPL0v1+9Utj9ju1FdP5617yq19Vip/cdx/lUzkeDJp8qpp9Nn/+FPcBIIFKG2OuQRCeNTNj4nq1lbrg0TnlmQOz+sxVwD1noTM3SDCQAfRhuVn1xbPFAUlOMXTL1PSHEhWMycyrKkpiNJsjRHb6XSp5m9xjP3yJ52zPa29VApp6683FO9XcLqGo1knx3vlAljisRXJcDaiVI+InBzNN6HZ2y6v3zS3ByzzvJ/Zar3fRzXT0DkEfX5M5uXT9rKqHLuF6CCHGRSXMrbcINQCBB5ZsVlFByCyWRCFUBk0J0rX59W5v704GTPxeZ2Ci64NTWRnuqHrJlF/cga/bgf+OBu36Xq91jE/DuuuzMm7TY0mKnJuHvEXwJLN41RalAVzn87pg1QSbdd70hQxaiauQG8SEIGCdurk+CzG2MUOFf/m3RA5hPpPF7hZTccBza4io0atc6NchEQvVmSR4SMCA9qiPWETfEihgACQME65H1XkSEvI/ChQF+5rQH00m1X7yNlMA2kvzqzM6YKNGdCqbi1bap9QEUBrSdANdR3jPHe1aZMX0Im9eIM8aQ4a8A21IdiHCF2wHw6mV0vXzLLcKj8u5TGeM+DqTLUWSkcr57+g77LVAcYgr9i+iZvYS+i+xmp0VD8Tz3cQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
